### ISSUE TITLE
The http/2 connection is no longer active and can therefore not be used to make new streams

### ISSUE THREAD

**Issue by jbg** [thosakwe/http2_client#1]
If a client is re-used this error eventually occurs:

```
Bad state: The http/2 connection is no longer active and can therefore not be used to make new streams.
#0      ClientConnection.makeRequest (package:http2/src/connection.dart:465:7)
#1      Http2Client._send.<anonymous closure> (package:http2_client/http2_client.dart:126:32)
<asynchronous suspension>
...
```

Presumably the server eventually closed the keep-alive connection and this wasn't handled gracefully.

**Comment by thosakwe** [comment]
1. Keep-Alive isn’t really a thing anymore in HTTP/2 afaik, because
connections are already kept alive
2. What do you mean by “reuse?” Did you close the client, and then attempt
to send requests through it?
3. Can you paste the code where you are using the client?

**Comment by jbg** [comment]
I guess the last sentence should just read _Presumably the server eventually closed the connection and this wasn't handled gracefully_. I didn't mean to imply that it had anything to do with keep-alive as a mechanism, but rather just the fact that the server is going to eventually close idle connections and this didn't seem to be handled gracefully.

By _re-used_ I just meant that I have one client object which I use for any number of requests. My app made three requests via it, which all worked, and then a minute or so later tried to make another request which failed with the above exception. Hence my assumption that the server probably closed the connection during that idle minute.

I switched back to http.Client in the app, but I'll try to put together a minimal test case that shows this behaviour and update this ticket.

**Comment by jbg** [comment]
```dart
import "dart:io";

import "package:http2_client/http2_client.dart";


main() async {
  var client = Http2Client(maxOpenConnections: Platform.numberOfProcessors);
  await doRequest(client);
  print("Sleeping for 30 seconds");
  await Future.delayed(const Duration(seconds: 30));
  await doRequest(client);
}

doRequest(Http2Client client) async {
  print("Sending request");
  var response = await client.get("https://www.cloudflare.com/");
  print("Got response status ${response.statusCode}");
  print("Read ${response.body.length} bytes from www.cloudflare.com");
}
```

Output:
```
Sending request
Got response status 200
Read 126216 bytes from www.cloudflare.com
Sleeping for 30 seconds
Sending request
Unhandled exception:
Bad state: The http/2 connection is no longer active and can therefore not be used to make new streams.
#0      ClientConnection.makeRequest (package:http2/src/connection.dart:465:7)
#1      Http2Client._send.<anonymous closure> (package:http2_client/http2_client.dart:126:32)
<asynchronous suspension>
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by thosakwe** [comment]
After a year and four months (sorry for the extremely long wait), this issue has been fixed. It turned out that the solution was to simply check if existing connections were closed, and form new ones if necessary.

https://pub.dev/packages/http2_client/versions/1.0.1
