### ISSUE TITLE
How to debug http2 with Charles

### ISSUE THREAD

**Issue by xlyasdasd** [thosakwe/http2_client#2]
I tried to use Charles to check the request ,but nothing is shown , any ideas?

**Comment by thosakwe** [comment]
I need more information to be able to help you out here...

**Comment by xlyasdasd** [comment]
In dart:io/HttpClient, request should be set a proxy on a specific port in code like this:
`(HttpClient client) {
client.findProxy = (uri) {
return "PROXY 172.16.2.176:8888";
};//proxy all request to 172.16.2.176:8888`
So that Charles could then find the request. Does http2 doesn't support a similar method?

**Comment by thosakwe** [comment]
I'm not sure if upstream `dart-lang/http2` supports proxies, but that's what this would depend on.

**Comment by thosakwe** [comment]
Hi, I'm going to go ahead and close this, as I'm not 100% sure that this package can support that. LMK if you need it reopened.
