### ISSUE TITLE
Query parameters cannot be carried

### ISSUE THREAD

**Issue by SpanishOnion** [thosakwe/http2_client#4]
my code:

`var response = await client.get('https://example.com/articles?abc=123&def=456');`

http2_client.dart，Lines 117

The result printed by parameter "path" is wrong

It does not carry query parameters
`
print(':path:${request.url.path}');// output: /articles

        var headers = [
          Header.ascii(':authority', request.url.authority),
          Header.ascii(':method', request.method),
          Header.ascii(':path', request.url.path),
          Header.ascii(':scheme', request.url.scheme),
        ];
`

The correct result should be `/articles?abc=123&def=456`

**Comment by thosakwe** [comment]
Thanks for pointing it out, send a pull request to fix it

**Comment by thosakwe** [comment]
Fixed in https://pub.dev/packages/http2_client/versions/1.0.2 - sorry for the long delay
